Models/BlogTable.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
//using MyFirstBlogSite.Data;
using MyFirstBlogSite.Models;


namespace MyFirstBlogSite.Models
{
    public class Blog
    {
        //private BlogDBContext context;
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Article { get; set; }

        public DateTime Date { get; set; }
    }
    /*public class BlogDBContext : DbContext
    {
        public BlogDBContext()
        { }
        public DbSet<Blog> BlogTables { get; set; }
        public object BlogTable { get; internal set; }
        public object BlogContext { get; internal set; }
    }*/
}

Models/ErrorViewModel.cs
using System;

namespace MyFirstBlogSite.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/BlogsController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyFirstBlogSite.Models;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyFirstBlogSite.Data;



// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace MyFirstBlogSite.Controllers
{
    public class BlogsController : Controller
    {
        private readonly BlogContext _context;
        // GET: /<controller>/
        public BlogsController(BlogContext context)
        {
            _context = context;
        }
        //GET: Blogs
        public async Task<IActionResult> Index()
        {
            /*var blogs = from e in db.BlogTables
                        orderby e.ID
                        select e;*/
            return View(await _context.Blogs.ToListAsync());
        }
        //GET: Blogs/Details
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blog = await _context.Blogs
                .FirstOrDefaultAsync(m => m.ID == id);
            if (blog == null)
            {
                return NotFound();
            }

            return View(blog);
        }

        //GET: Blogs/Create
        public IActionResult Create()
        {
            return View();
        }

        //POST: Blogs/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Author,Article,SubmitDate")] Blog blog)
        {
            if (ModelState.IsValid)
            {
                _context.Add(blog);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));

            }
            return View(blog);
        }
        
        //GET:Blogs/Edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blog = await _context.Blogs.FindAsync(id);
            if (blog == null)
            {
                return NotFound();
            }

            return View(blog);
        }

        //Post: Blogs/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Author,Article,SubmitDate")] Blog blog)
        {
            if (id != blog.ID)
            {
                return NotFound();
            }

            //var blog = await _context.Blogs.FindAsync(id);
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(blog);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BlogExists(blog.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(blog);
        }

        //GET: Blogs/Delete
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blog = await _context.Blogs
                .FirstOrDefaultAsync(m => m.ID == id);
            if (blog == null)
            {
                return NotFound();
            }

            return View(blog);
        }

        // POST: Blogs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var blog = await _context.Blogs.FindAsync(id);
            _context.Blogs.Remove(blog);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BlogExists(int id)
        {
            return _context.Blogs.Any(e => e.ID == id);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MyFirstBlogSite.Models;
using MySql.Data.MySqlClient;
using System.Web;
namespace MyFirstBlogSite.Controllers
{
    public class HomeController : Controller
    {
        //private readonly ILogger<HomeController> _logger;

        /*public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }*/

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Article()
        {
            return View();
        }

        /*public IActionResult SubmitArticle()
        {
            //MySqlConnection conn = new MySqlConnection("server=localhost;database=mysqltest;uid=root;pwd=root");

            //MySqlCommand cmd = null;
            //string cmdString = "";
            //conn.Open();

            //cmdString = "insert into student values(" + textBox1.Text + ",'" + textBox2.Text + "'," + textBox3.Text + ",'" + textBox4.Text + "'," + textBox5.Text + ")";

            //cmd = new MySqlCommand(cmdString, conn);
            //cmd.ExecuteNonQuery();

            //conn.Close();
            
            return View();
        }

        public IActionResult username() 
        {
            return View();
        }*/

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        
    }
}

Views/Blogs/Create.cshtml
@model MyFirstBlogSite.Models.Blog

@{
    ViewData["Title"] = "Create";

}

<h2>Create</h2>

<h4>Blog</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Author" class="control-label"></label>
                <input asp-for="Author" class="form-control" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Article" class="control-label"></label>
                <input asp-for="Article" class="form-control" />
                <span asp-validation-for="Article" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


@section Scripts {
     @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Blogs/Index.cshtml
@model IEnumerable<MyFirstBlogSite.Models.Blog>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Author)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Article)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Author)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Article)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                </td>
            </tr>
         }
    </tbody>
</table>

Views/Blogs/username.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Username Login";
}
<!DOCTYPE html>
<head>
    
</head>
<style>
.center{
    text-align:center;
}
h3{
    color: white;
    border:3px solid white;
}
</style>
<body style="background-color:powderblue" ;>

    <div class="center">
        <form action="/home" target="_blank" method="POST" name="username">
            <h3>User Name:</h3>
            <input type="text" id="username" name="username"><br>
            <br /><h3>Password:</h3>
            <input type="password" id="pass" name="password"
                   minlength="8" required><br />
            <input type="submit" value="Submit" OnClick="SubmitForm">
        </form>
    </div>

</body>

Views/Home/Article.cshtml
@model MyFirstBlogSite.Models.Blog

@{
    ViewData["Title"] = "Blog Post 1";

}

<!DOCTYPE html>
<html>
<head>
    <title>Page Title</title>
</head>
<style>
    .center {
        text-align: center;
    }

    h2 {
        border: 3px solid white;
    }

    p {
        border: 1px solid black;
    }
</style>
<body style="background-color:powderblue" ;>

    <div class="center">
        <h2>This is my 1st Blog Post</h2>
        <p>This is where I put info/text for my 1st blog post.</p>
    </div>
</body>
</html>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-1">Austin's 1st Blog</h1>
</div>

<!DOCTYPE html>
<html>
<head>
    <title>Page Title</title>
</head>
<style>
    .center {
        text-align: center;
    }

    h2 {
        border: 3px solid white;
    }

    p {
        border: 1px solid black;
    }

    ul {
        text-align: left;
    }

    ol {
        text-align: left;
        border: 1px solid red;
    }
</style>
<body style="background-color:powderblue" ;>

    <div class="center">
        <h2>This is my 1st Blog Post</h2>
        <p>This is where I put info/text for my 1st blog post.</p>

        <h2>2nd Blog Post: The 3 Things You Need Before Leaving The House:</h2>

        <ul>
            <li>Phone <input id="Checkbox1" type="checkbox" /></li>
            <li>Keys <input id="Checkbox1" type="checkbox" /></li>
            <li>Wallet <input id="Checkbox1" type="checkbox" /></li>
        </ul>

        <h2>3rd Blog Post: The 3 Things You Need To Survive</h2>

        <ol>
            <li>Food <input id="Checkbox1" type="checkbox" /></li>
            <li>Shelter <input id="Checkbox1" type="checkbox" /></li>
            <li>Money <input id="Checkbox1" type="checkbox" /></li>
        </ol>

        <h2 style="background-color:white;">This Is My 4th Blog Post</h2>

        <p style="background-color:red; text-align: left; color:white;">
            Here is where I have a red background color and white text for my paragraph
        </p>
    </div>

    <h2 text-align="left">5th Blog Post: This Is A Drop Down List</h2>
    <p text-align="left">
        <select>
            <option value="one">One</option>
            <option value="two">Two</option>
            <option value="three">Three</option>
            <option value="four">Four</option>
        </select>
        <input type="submit" value="Submit">
    </p>
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyFirstBlogSite</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-1">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyFirstBlogSite</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                      @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Username">Username Login</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Blog" asp-action="Index">Submit an Article</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Blogs" asp-action="Index">Articles</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MyFirstBlogSite - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>